FROM node:13.12.0-alpine as build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn

COPY . .

RUN yarn run build


FROM nginx:stable-alpine

COPY --from=build /app/build /bin/wwww

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]